import Head from "next/head";
import Prismic from '@prismicio/client';

import BackgroundImg from "../../../components/BgSite";
import SideLine from "../../../components/BgSite/SideLine";
import Footer from "../../../components/Footer";
import Newsletter from "../../../components/Newsletter";
import TopHead from "../../../components/TopHead";
import CategoriesPosts from '../../../components/CategoriesPosts';
import BlogPost from "../../../components/BlogPost";
import SeeMore from "../../../components/SeeMore";
import Header from "../../../components/Header";

import { HomeContainer } from '../../../styles/HomeStyle';
import { BlogPostContent } from "../../../styles/PostStyle";
import { getPrismicClient } from "../../../services/prismic";

function Postagem({ post }) {
  return (
    <div id="contato">
      <Head>
        <title>{post.title} | Intervalo Londrina</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <BackgroundImg />
      <SideLine />
      <HomeContainer>
        <main className="container">
          <TopHead />
          <CategoriesPosts />
          <BlogPostContent>
            <BlogPost post={post}/>
            <SeeMore />
          </BlogPostContent>
          <Newsletter />
        </main>
      </HomeContainer>
      <Footer />
    </div>
  )
}

export default Postagem;

export const getStaticPaths = async () => {
  const prismic = getPrismicClient();
  const projetos = await prismic.query([
    Prismic.predicates.at('document.type', 'postagem')
  ]);

  const paths = projetos.results.map(projeto => ({
    params: {
      slug: projeto.uid
    }
  }));

  return {
    paths,
    fallback: true,
  }
}

export const getStaticProps = async context => {
  const prismic = getPrismicClient();
  const { slug } = context.params

  const response = await prismic.getByUID('postagem', String(slug), {});
  
  // const postagens = projectResponse.results.map(post => ({
  //     id: post.id,
  //     slug: post.uid,
  //     date: post.data.date,
  //     title: post.data.title,
  //     author: post.data.author,
  //     category: post.data.categories,
  //     resume: post.data.resume,
  //     text: post.data.text,
  //     image: post.data.image.url,
  //   }));

  const post = {
    slug: response.slugs,
    title: response.data.title,
    author: response.data.author,
    date: response.data.date,
    categories: response.data.categories,
    image: response.data.image.url,
    text: response.data.text,
  }
    
    console.log(response)

  return {
    props: {
      post
    },
    revalidate: 86400
  };
}