import Head from 'next/head';
import Image from 'next/image';
import BackgroundImg from '../components/BgSite';
import SideLine from '../components/BgSite/SideLine';
import CategoriesPosts from '../components/CategoriesPosts';
import Header from '../components/Header';
import LogoSite from '../components/LogoSite';
import PostCardHome from '../components/PostCardHome';

import TitleAbout from '../components/TitleAbout';
import TopHead from '../components/TopHead';
import { HomeContainer } from '../styles/HomeStyle';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Intervalo Londrina</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Header /> */}
      <BackgroundImg />
      <SideLine />
      <HomeContainer>
        <main className="container">
          <TopHead />
          <CategoriesPosts />
          <div className="home_subtitle">
            <div className="sub_line"></div>
            <h1>Últimos Posts</h1>
            <div className="sub_line"></div>
          </div>
          <PostCardHome />
        </main>
      </HomeContainer>
    </>
  )
}
